--Written in Snowflake 
SELECT 
    T.TRANSACTION_ID
    --Concatenate Relevant Digits
    ,'GB'||S.CHECK_DIGITS||S.SWIFT_CODE||REPLACE(T.sort_code,'-')||T.ACCOUNT_NUMBER AS IBAN
FROM PD2023_WK02_TRANSACTIONS AS T
INNER JOIN PD2023_WK02_SWIFT_CODES AS S
ON T.BANK = S.BANK;
